### ISSUE TITLE
运行脚本没反应

### ISSUE THREAD

**Issue by Friendar** [hcy2206/MAA_Notify_Script#1]
![Snipaste_2024-05-29_21-40-19](https://github.com/hcy2206/MAA_Notify_Script/assets/66019042/d5d3c50e-64d3-4df3-a86e-803619992fda)

如图, 在.py文件里面添加了key, 然后添加到了maa结束后脚本, 在maa任务已全部完成后会运行脚本, 但是脚本结束了软件上没收到信息, 想问一下是哪里做的不对吗

**Comment by Friendar** [comment]
方便的话可以加微吗1143577196, github上的不是很勤快

**Comment by hcy2206** [comment]
bug已修复，新版本已经发布
